name: Test setup-tenv
on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        tool: [tofu, terraform]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup tenv
        uses: ./
        with:
          tool: ${{ matrix.tool }}
          tool-version: latest
      - name: Verify tenv
        run: |
          which tenv
          tenv version
      - name: Verify tool
        run: |
          which ${{ matrix.tool }}
          ${{ matrix.tool }} version

